### ISSUE TITLE
For scalable approach(in CI), the tests would be executed in TestNG Suite or Maven CLI scripts

### ISSUE THREAD

**Issue by sadeesh-sdet** [tejaswinidevi/ParaBank#3]
I see, the instructions are given to execute the tests with TestNG. Since it is a maven project and in order to execute the tests in CI/CD, compare to TestNG - Maven CLI script like ```mvn clean install``` are quite handy and scalable approach. What is your thought?

**Comment by tejaswinidevi** [comment]
Yes sir, I normally use `mvn clean` and `mvn install `commands to run automation scripts so that i can have test reports generated using serenity. As the problem statement mentioned the usage of testng, i have learnt and used it. But as the code I have written is based on BDD using maven, I think rather than testng, `mvn clean` and `mvn install` will be better.
